/**
 * art-gallery-worker — serves the gallery's R2 contents with CORS headers so
 * the static site can load them cross-origin (prevents ERR_BLOCKED_BY_ORB),
 * and generates AI overviews for each artwork via Google Gemini (vision).
 *
 * Routes:
 *   GET /                      → JSON listing of objects in the `art` folder
 *                                { "files": ["sunset.jpg", ...] }
 *                                (directory markers like `art/` are filtered out)
 *   GET /img/<key>             → streams the image bytes with a correct
 *                                Content-Type and Access-Control-Allow-Origin
 *   GET /img/<key>?w=<px>      → resizes the image at the edge to the given
 *                                width (CF image resizing → webp)
 *   GET /describe/<key>        → JSON { "name", "description" } generated by
 *                                Gemini vision from the actual image (cached)
 */

const ART_FOLDER = 'art';
const CACHE_FOLDER = 'descriptions';

/** CORS: allow the static site (any origin) to read listing/images/descriptions. */
const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type'
};

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'no-cache',
      ...CORS_HEADERS
    }
  });
}

/** Map common image extensions to a MIME type. */
const MIME = {
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
  avif: 'image/avif',
  gif: 'image/gif',
  bmp: 'image/bmp',
  svg: 'image/svg+xml'
};

function mimeFor(key) {
  const ext = (key.split('.').pop() || '').toLowerCase();
  return MIME[ext] || 'application/octet-stream';
}

/**
 * List every real object under the `art` folder.
 *
 * R2's bucket binding exposes `list({ prefix, delimiter })`. It is paginated,
 * so we keep calling until a returned list is truncated, then concatenate.
 *
 * `delimiter` is deliberately omitted so we get all keys. Keys ending in a `/`
 * are directory markers (pseudo-folders, e.g. `art/`), not real files, so we
 * skip them — otherwise they'd produce a broken image tile.
 */
async function listFiles(bucket) {
  const files = [];
  let cursor;

  do {
    const listed = await bucket.list({
      prefix: `${ART_FOLDER}/`,
      cursor
    });

    for (const obj of listed.objects) {
      if (obj.key.endsWith('/')) continue; // skip directory markers
      files.push(obj.key);
    }

    cursor = listed.truncated ? listed.cursor : undefined;
  } while (cursor);

  return files;
}

/**
 * Stream an object's bytes back to the client with the right Content-Type and
 * permissive CORS. Returns a 404 if the key doesn't exist.
 */
async function serveImage(bucket, key) {
  const object = await bucket.get(key);

  if (object === null) {
    return json({ error: `Object not found: ${key}` }, 404);
  }

  const headers = {
    'Content-Type': mimeFor(key),
    'Content-Length': String(object.size),
    'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    ...CORS_HEADERS
  };

  // Stream the body directly from R2 — no buffering the whole image in memory.
  return new Response(object.body, { headers });
}

const IMG_RESIZE_PASS_HEADER = 'x-img-resize';

/**
 * Encode a Uint8Array of bytes as base64.
 *
 * Builds the string in chunks of at most 0x8000 bytes so we never hit the
 * engine's per-spread argument limit (which a literal
 * `btoa(String.fromCharCode(...bigArray))` would blow past for large images).
 * Works in the Workers runtime (no reliance on a global `btoa`).
 */
function bytesToBase64(bytes) {
  const CHUNK = 0x8000; // 32768 — safely under any call-arg limit
  let binary = '';
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode.apply(
      null,
      bytes.subarray(i, i + CHUNK)
    );
  }
  return btoa(binary);
}

/**
 * Call Google Gemini (vision) to get an artistic name + short description for
 * an image, given its bytes and content type.
 *
 * Requires `env.GEMINI_API_KEY` to be set as a Worker secret.
 *
 * @returns {Promise<{name: string, description: string}>}
 */
async function describeWithGemini(bytes, contentType, apiKey, model) {
  const endpoint =
    `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const body = {
    contents: [
      {
        parts: [
          {
            text:
              'You are an art curator and poet. Given this photograph, propose: ' +
              '1) a short evocative title (5 words or fewer, no quotes, no leading "Title:"), ' +
              '2) a 1-sentence description (about 15-25 words) highlighting the beauty, ' +
              'mood, light, color, or composition. ' +
              'Return ONLY valid JSON like: {"name":"...","description":"..."}'
          },
          {
            inline_data: {
              mime_type: contentType,
              data: bytes // base64
            }
          }
        ]
      }
    ],
    generationConfig: { temperature: 0.8, maxOutputTokens: 160 }
  };

  const resp = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Gemini returned ${resp.status}: ${text.slice(0, 200)}`);
  }

  const data = await resp.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';

  try {
    // Gemini sometimes wraps the JSON in a ```json fenced block or adds prose
    // before/after it. Robustly extract just the JSON object: everything from
    // the first "{" to the last "}", then parse that.
    const first = text.indexOf('{');
    const last = text.lastIndexOf('}');
    if (first === -1 || last === -1 || last < first) {
      throw new Error('No JSON object found in Gemini response');
    }
    const cleaned = text.slice(first, last + 1).trim();
    const parsed = JSON.parse(cleaned);
    return {
      name: (parsed.name || '').trim() || 'Untitled',
      description: (parsed.description || '').trim()
    };
  } catch (err) {
    // Fallback: use the raw text as the description.
    const cleaned = text
      .replace(/["'`\n\r]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
    return { name: 'Untitled', description: cleaned };
  }
}

/**
 * Return the cached description for a key if present, else null.
 * Descriptions are stored inside the same bucket under `descriptions/<hash>.json`.
 */
async function getCached(bucket, cacheKey) {
  const obj = await bucket.get(`${CACHE_FOLDER}/${cacheKey}.json`);
  if (obj === null) return null;
  return await obj.json();
}

export default {
  async fetch(request, env, ctx) {
    const bucket = env.ART_BUCKET;

    // Preflight for cross-origin requests from the static site.
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    if (request.method !== 'GET') {
      return json({ error: 'Method not allowed' }, 405);
    }

    const url = new URL(request.url);
    const pathname = url.pathname;

    // /describe/<key> → AI overview for one image.
    if (pathname.startsWith('/describe/')) {
      const artKey = pathname.slice('/describe/'.length);
      if (!artKey) return json({ error: 'Missing object key' }, 400);

      if (!env.GEMINI_API_KEY) {
        return json(
          { error: 'AI is not configured (set the GEMINI_API_KEY secret).' },
          503
        );
      }

      // Cache key = hash of the art key (so URLs stay safe in the path).
      const cacheKey = encodeURIComponent(artKey);

      // 1. Return cached result if available.
      const cached = await getCached(bucket, cacheKey);
      if (cached) {
        return json(cached);
      }

      // 2. Read the image and ask Gemini (keep it in try/catch so a failure in
      //    any step returns a clean 502 instead of crashing the worker).
      try {
        const object = await bucket.get(artKey);
        if (object === null) {
          return json({ error: `Object not found: ${artKey}` }, 404);
        }
        const arrayBuffer = await object.arrayBuffer();
        const bytes = bytesToBase64(new Uint8Array(arrayBuffer));

        const result = await describeWithGemini(
          bytes,
          mimeFor(artKey),
          env.GEMINI_API_KEY,
          env.GEMINI_MODEL || 'gemini-2.5-flash-lite'
        );

        // 3. Cache it (fire-and-forget so we don't block the response).
        ctx.waitUntil(
          bucket.put(`${CACHE_FOLDER}/${cacheKey}.json`, JSON.stringify(result))
        );

        return json(result);
      } catch (err) {
        console.error('describe error', err);
        return json({ error: `Could not generate overview: ${err.message}` }, 502);
      }
    }

    // /img/<key> → serve the object bytes (optionally resized).
    if (pathname.startsWith('/img/')) {
      const imgKey = pathname.slice('/img/'.length);
      if (!imgKey) return json({ error: 'Missing object key' }, 400);

      const width = parseInt(url.searchParams.get('w') || '', 10);

      // Already a resize pass → serve the raw bytes (the size is baked in).
      if (request.headers.get(IMG_RESIZE_PASS_HEADER) === '1') {
        return serveImage(bucket, imgKey);
      }

      // Request a resized variant at the edge if a width was provided.
      if (Number.isFinite(width) && width > 0) {
        const resizeUrl = new URL(url);
        resizeUrl.searchParams.delete('w');
        const resizeRequest = new Request(resizeUrl, {
          headers: {
            ...request.headers,
            [IMG_RESIZE_PASS_HEADER]: '1'
          }
        });
        const transformed = await fetch(resizeRequest, {
          cf: {
            image: {
              width,
              fit: 'scale-down',
              format: 'webp',
              sharpness: 0
            }
          }
        });
        const responseHeaders = new Headers(transformed.headers);
        Object.entries(CORS_HEADERS).forEach(([k, v]) =>
          responseHeaders.set(k, v)
        );
        responseHeaders.set('Cache-Control', 'public, max-age=31536000, immutable');
        return new Response(transformed.body, {
          status: transformed.status,
          headers: responseHeaders
        });
      }

      return serveImage(bucket, imgKey);
    }

    // Anything else → the folder listing.
    try {
      const files = await listFiles(bucket);
      return json({ files });
    } catch (err) {
      return json({ error: `Failed to list objects: ${err.message}` }, 500);
    }
  }
};
